### PR TITLE
fuck you

### PR DESCRIPTION
**Pull request by nbs32k**

### CODE REVIEW

**Comment by nutzboi** [comment]
fuck off

**Comment by nbs32k** [comment]
pull it

**Comment by nutzboi** [comment]
the trigger?

**Comment by nbs32k** [comment]
fuck off and pull it, you're literally putting junk

**Comment by nbs32k** [comment]
don't you dare to close this

**Comment by nutzboi** [comment]
it's not fucking junk, suck my balls. what if i want to add more lines in the scope? that would fuck it up.

**Comment by nbs32k** [comment]
i just cleaned ur current code, you also abandoned the project so you wont update it. Pull my shit, you wont add new code so you can create new brackets

**Comment by nutzboi** [comment]
true

**Comment by nbs32k** [comment]
yeah go pull it, i'm such a fan of nutzboi's cpp creations

**Comment by nutzboi** [comment]
then prove you are a fan of nutzboi's cpp creations. star the repo, go a ahead.

**Comment by nbs32k** [comment]
starred.

**Comment by nbs32k** [comment]
(even tho it's horrid)

**Comment by nbs32k** [comment]
ez

**Pull request merged**
